menu:
  about: /about
favicon:
  enable: true
  icon: /image/icon/vista_messenger.jpg
profile:
  enable: true
  author: ''
  avatar: ''  # Your avatar image, for example, https://avatars.githubusercontent.com/username
  avatar_link: '' # The link you click on the avatar and jump to, for example, https://github.com/username
  social: # you can customize which and how many social links to show
    - name: Github
      link: '' # https://github.com/username
      icon: /image/icon/github.png
    - name: Bilibili
      link: '' # https://space.bilibili.com/youruid
      icon: /image/icon/bilibili.png

# 音乐栏，目前为本地，可添加多首
music:
  enable: false
  autoplay: false
  songs:
    - title: ''
      artist: ''
      cover: ''
      url: ''

# Comment
# Params: disable/twikoo/gitalk
comment:
  use: disable
  showOnAbout: true   

  # twikoo settings
  # https://github.com/imaegoo/twikoo
  twikoo:
    env: # Your Environment Url is there
  
  # https://github.com/gitalk/gitalk
  gitalk:
    cid:    # ClientID
    csecret:   #Client Secret
    repo:
    own:
    admin:
  
math:
  enable: true
  engine: mathjax